services:
  app:
    build: .
    container_name: usefultraining-gradle-app
    volumes:
      - ./:/gradleproject
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usefultraining
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 37373
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54333:5432
    expose:
      - 5432
    networks:
      - ktor-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
networks:
  ktor-network:
    driver: bridge